version: "3.8"
services:
  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./frontend/src:/app/src
    depends_on:
      - backend
    command: npm run dev -- --host
