apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend-deployment
          image: __BACKEND_IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_USERNAME
              value: __MONGODB_USERNAME__
            - name: MONGODB_PASSWORD
              value: __MONGODB_PASSWORD__
